### ISSUE TITLE
Add glpi.createObjects

### ISSUE THREAD

**Issue by wilcorrea** [vitorbari/glpi-webservice-php-wrapper#1]
Oi vitor, tem alguma sugestão para usar o `glpi.createObjects`?

Estou desenvolvendo um módulo de integração para o GLPI aqui na empresa também. Estava atá ficando um pouco parecido com o que você está fazendo.

Eu vi que está usando SOAP, eu estava usando o XMLRPC, e não estava funcionando. Consegue me dizer se daria certo com SOAP?

**Comment by vitorbari** [comment]
William,

Sim, a utilização do webservice via SOAP funciona perfeitamente. 

Seguindo o padrão que eu utilizei para os outros métodos, daria para implementar o método createObjects de forma simples, mas seria melhor implementar uma método específico para cada tipo de objeto que ele pode criar.

**Comment by wilcorrea** [comment]
Fiz um fork aqui e vou fazer uns testes, qualquer coisa mando PR ae ; )

**Comment by vitorbari** [comment]
Beleza. Se precisar de algo, me avise.

**Comment by wilcorrea** [comment]
Na minha implementação aqui eu estava pegando o hash e mantendo ele em um
arquivo para não ter que levantar uma nova sessão a cada requisição.
Vi que você não deixou esse recurso. É uma má prática essa de reaproveitar
o hash? Eu estava salvando um arquivo e a cada request eu tentava rodar um
'glpi.getMyInfo' com o hash, se ele já estivesse expirado eu faria um novo
login. Estava meio que usando ele como um token oauth, rs. Posso
implementar isso aqui ou não?

**Comment by vitorbari** [comment]
Nas minhas utilizações eu nunca precisei manter a sessão, mas acredito que pode ser útil sim.

**Comment by wilcorrea** [comment]
Eu implementei o listObjects 

``` php
    /**
     * @param $itemtype
     * @param array $params
     * @return mixed
     */
    public function listObjects($itemtype, $params = array())
    {
        return $this->client->call(array(
                'method'   => 'glpi.listObjects',
                'session'  => $this->getSessionHash(),
                'itemtype' => $itemtype
            ) + $params);
    }

   $glpi->listObjects('change_problem')
```

E ele me retornou 

``` json
[{"id":"1"},{"id":"2"},{"id":"3"},{"id":"4"},{"id":"5"},{"id":"6"},{"id":"7"},{"id":"8"},{"id":"9"},{"id":"10"},{"id":"11"},{"id":"12"},{"id":"13"}]
```

Sendo que na tabela tem os campos que eu preciso

```
id  int(11) NO  PRI     auto_increment
changes_id  int(11) NO  MUL 0   
problems_id int(11) NO  MUL 0   
```

No select `SELECT problems_id FROM glpi_changes_problems` lista essa mesma quantidade de registros, mas a API não expõe todas colunas e não me deixa pesquisar.

Chegou a ter algum problema parecido?

**Comment by vitorbari** [comment]
Não sei qual a lógica que é utilizada para o retorno dos campos em cada itemtype.

**Comment by vitorbari** [comment]
O método `getObject` retorna os campos changes_id e problems_id?

**Comment by wilcorrea** [comment]
Retorna não : (

**Comment by vitorbari** [comment]
Experimenta utilizar `glpi.listInventoryObjects` ao invés de `glpi.listObjects`

**Comment by vitorbari** [comment]
Este outro método tem um parâmetro `columns`

**Comment by wilcorrea** [comment]
O `listInventoryObjects` retorna um `[]` (array vazio) no meu caso, porque não estou usando dispositivos, só chamados, problemas e mudanças.
Vou tentar passar o `columns`

**Comment by wilcorrea** [comment]
Mesmo passando o parâmetro `columns` só lista o `id`

``` php
    $this->glpi->listObjects('change_problem', ['columns' => ['id', 'changes_id', 'problems_id'] ]);

    /**
     * @param $itemtype
     * @param array $params
     * @return mixed
     */
    public function listObjects($itemtype, $params = array())
    {
        return $this->soap->call(array(
                'method'   => 'glpi.listObjects',
                'session'  => $this->getSessionHash(),
                'itemtype' => $itemtype
            ) + $params);
    }
```

**Comment by vitorbari** [comment]
O parâmetro `columns` é para o método `listInventoryObjects` e deve ser uma string com os campos separados por virgula ao invés de um array.

**Comment by vitorbari** [comment]
https://forge.glpi-project.org/projects/webservices/wiki/Specifications_Inventory

**Comment by wilcorrea** [comment]
Vou dar uma olhada nisso. Estou usando esse link aqui como referência: https://forge.glpi-project.org/projects/webservices/wiki/En_devguide#Provided-Methods

**Comment by wilcorrea** [comment]
Desisti de usar a API e fiz um select : (
